# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
optimizer_runs = 200
solc_version = "0.8.33"
evm_version = "prague"
fs_permissions = [{ access = "read-write", path = "./" }]
sparse_mode = true
remappings = [
    "CMTAT/=lib/CMTAT/contracts/"
]

[lint]
lint_on_build = false

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
mainnet-sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
arbitrum-sepolia = "https://arbitrum-sepolia.gateway.tenderly.co"

[etherscan]
mainnet-sepolia = { key = "${ETHERSCAN_TOKEN}", chain = 11155111, url = "https://api.etherscan.io/v2/api?chainid=11155111" }
arbitrum-sepolia = { key = "${ETHERSCAN_TOKEN}", chain = 421614, url = "https://api.arbiscan.io/v2/api?chainid=421614" }
